package dev.guogaology.outer;
import net.minecraft.resources.Identifier;
/** Compatibility boundary for the authorized donor module; the host owns shared items. */
public final class GuogaologyMod {
    public static final org.slf4j.Logger LOGGER=org.slf4j.LoggerFactory.getLogger("guogaology-outer");
    private static String alias(String name){return switch(name){
            case "bashicu_block" -> "guogaology:ordinal_bricks";
            case "gummy_block" -> "guogaology:amber_guogao";
            case "fruit_cake" -> "guogaology:guogao_slice";
            case "christmas_light" -> "guogaology:amber_light";
            case "laver_log" -> "guogaology:laver_vein";
            case "laver_planks" -> "guogaology:laver_planks";
            case "laver_leaves" -> "guogaology:giant_laver";
            case "lho_glass" -> "guogaology:absence_glass";
            case "ordinal_stone" -> "minecraft:stone";
            case "cobbled_ordinal_stone" -> "minecraft:cobblestone";
            case "andesite_ordinal_stone" -> "minecraft:andesite";
            case "diorite_ordinal_stone" -> "minecraft:diorite";
            case "granite_ordinal_stone" -> "minecraft:granite";
            case "tuff_ordinal_stone" -> "minecraft:tuff";
            case "hell_ordinal_stone" -> "minecraft:netherrack";
            case "christmas_log" -> "minecraft:spruce_log";
            case "christmas_wood" -> "minecraft:spruce_wood";
            case "christmas_stripped_log" -> "minecraft:stripped_spruce_log";
            case "christmas_stripped_wood" -> "minecraft:stripped_spruce_wood";
            case "hell_christmas_log" -> "minecraft:dark_oak_log";
            case "hell_christmas_wood" -> "minecraft:dark_oak_wood";
            case "hell_christmas_stripped_log" -> "minecraft:stripped_dark_oak_log";
            case "hell_christmas_stripped_wood" -> "minecraft:stripped_dark_oak_wood";
            case "googology_portal", "guogaology_portal" -> "guogaology:guogao_portal";
            case "googology_portal_frame", "guogaology_portal_frame" -> "guogaology:guogao_portal_frame";
            case "christmas_planks" -> "minecraft:spruce_planks";
            case "christmas_stairs" -> "minecraft:spruce_stairs";
            case "christmas_slab" -> "minecraft:spruce_slab";
            case "christmas_door" -> "minecraft:spruce_door";
            case "christmas_trapdoor" -> "minecraft:spruce_trapdoor";
            case "christmas_fence" -> "minecraft:spruce_fence";
            case "christmas_fence_gate" -> "minecraft:spruce_fence_gate";
            case "christmas_button" -> "minecraft:spruce_button";
            case "christmas_pressure_plate" -> "minecraft:spruce_pressure_plate";
            case "christmas_sign" -> "minecraft:spruce_sign";
            case "christmas_wall_sign" -> "minecraft:spruce_wall_sign";
            case "christmas_boat" -> "minecraft:spruce_boat";
            case "christmas_sapling" -> "minecraft:spruce_sapling";
            case "hell_christmas_planks" -> "minecraft:dark_oak_planks";
            case "hell_christmas_stairs" -> "minecraft:dark_oak_stairs";
            case "hell_christmas_slab" -> "minecraft:dark_oak_slab";
            case "hell_christmas_door" -> "minecraft:dark_oak_door";
            case "hell_christmas_trapdoor" -> "minecraft:dark_oak_trapdoor";
            case "hell_christmas_fence" -> "minecraft:dark_oak_fence";
            case "hell_christmas_fence_gate" -> "minecraft:dark_oak_fence_gate";
            case "hell_christmas_button" -> "minecraft:dark_oak_button";
            case "hell_christmas_pressure_plate" -> "minecraft:dark_oak_pressure_plate";
            case "hell_christmas_sign" -> "minecraft:dark_oak_sign";
            case "hell_christmas_wall_sign" -> "minecraft:dark_oak_wall_sign";
            case "hell_christmas_boat" -> "minecraft:dark_oak_boat";
            case "hell_christmas_sapling" -> "minecraft:dark_oak_sapling";
            case "loquat_log" -> "minecraft:oak_log";
            case "loquat_wood" -> "minecraft:oak_wood";
            case "loquat_planks" -> "minecraft:oak_planks";
            case "loquat_stairs" -> "minecraft:oak_stairs";
            case "loquat_slab" -> "minecraft:oak_slab";
            case "loquat_door" -> "minecraft:oak_door";
            case "loquat_trapdoor" -> "minecraft:oak_trapdoor";
            case "loquat_fence" -> "minecraft:oak_fence";
            case "loquat_fence_gate" -> "minecraft:oak_fence_gate";
            case "loquat_button" -> "minecraft:oak_button";
            case "loquat_pressure_plate" -> "minecraft:oak_pressure_plate";
            case "loquat_sign" -> "minecraft:oak_sign";
            case "loquat_wall_sign" -> "minecraft:oak_wall_sign";
            case "loquat_boat" -> "minecraft:oak_boat";
            case "loquat_stripped_log" -> "minecraft:stripped_oak_log";
            case "loquat_stripped_wood" -> "minecraft:stripped_oak_wood";
            case "hell_loquat_log" -> "minecraft:oak_log";
            case "hell_loquat_wood" -> "minecraft:oak_wood";
            case "hell_loquat_planks" -> "minecraft:oak_planks";
            case "hell_loquat_stairs" -> "minecraft:oak_stairs";
            case "hell_loquat_slab" -> "minecraft:oak_slab";
            case "hell_loquat_door" -> "minecraft:oak_door";
            case "hell_loquat_trapdoor" -> "minecraft:oak_trapdoor";
            case "hell_loquat_fence" -> "minecraft:oak_fence";
            case "hell_loquat_fence_gate" -> "minecraft:oak_fence_gate";
            case "hell_loquat_button" -> "minecraft:oak_button";
            case "hell_loquat_pressure_plate" -> "minecraft:oak_pressure_plate";
            case "hell_loquat_sign" -> "minecraft:oak_sign";
            case "hell_loquat_wall_sign" -> "minecraft:oak_wall_sign";
            case "hell_loquat_boat" -> "minecraft:oak_boat";
            case "hell_loquat_stripped_log" -> "minecraft:stripped_oak_log";
            case "hell_loquat_stripped_wood" -> "minecraft:stripped_oak_wood";
            case "hell_christmas_leaves" -> "guogaology:dread_leaves";
            case "dread_log" -> "guogaology:dread_log";
            case "dread_leaves" -> "guogaology:dread_leaves";
            case "omega_stone" -> "guogaology:omega_material";
            case "omega_ore" -> "guogaology:omega_ore";
            case "omega_block" -> "guogaology:omega_block";
            case "omega_pickaxe" -> "guogaology:omega_pickaxe";
            case "omega_sword" -> "guogaology:omega_sword";
            case "omega_helmet" -> "guogaology:omega_helmet";
            case "omega_chestplate" -> "guogaology:omega_chestplate";
            case "omega_leggings" -> "guogaology:omega_leggings";
            case "omega_boots" -> "guogaology:omega_boots";
            case "hell_omega_ore" -> "guogaology:nether_omega_ore";
            case "epsilon_stone" -> "guogaology:epsilon_material";
            case "epsilon_ore" -> "guogaology:epsilon_ore";
            case "epsilon_block" -> "guogaology:epsilon_block";
            case "epsilon_pickaxe" -> "guogaology:epsilon_pickaxe";
            case "epsilon_sword" -> "guogaology:epsilon_sword";
            case "epsilon_helmet" -> "guogaology:epsilon_helmet";
            case "epsilon_chestplate" -> "guogaology:epsilon_chestplate";
            case "epsilon_leggings" -> "guogaology:epsilon_leggings";
            case "epsilon_boots" -> "guogaology:epsilon_boots";
            case "hell_epsilon_ore" -> "guogaology:nether_epsilon_ore";
            case "gamma_stone" -> "guogaology:gamma_material";
            case "gamma_ore" -> "guogaology:gamma_ore";
            case "gamma_block" -> "guogaology:gamma_block";
            case "gamma_pickaxe" -> "guogaology:gamma_pickaxe";
            case "gamma_sword" -> "guogaology:gamma_sword";
            case "gamma_helmet" -> "guogaology:gamma_helmet";
            case "gamma_chestplate" -> "guogaology:gamma_chestplate";
            case "gamma_leggings" -> "guogaology:gamma_leggings";
            case "gamma_boots" -> "guogaology:gamma_boots";
            case "hell_gamma_ore" -> "guogaology:nether_gamma_ore";
            case "true_omega_stone" -> "guogaology:true_omega_material";
            case "true_omega_ore" -> "guogaology:true_omega_ore";
            case "true_omega_block" -> "guogaology:true_omega_block";
            case "true_omega_pickaxe" -> "guogaology:true_omega_pickaxe";
            case "true_omega_sword" -> "guogaology:true_omega_sword";
            case "true_omega_helmet" -> "guogaology:true_omega_helmet";
            case "true_omega_chestplate" -> "guogaology:true_omega_chestplate";
            case "true_omega_leggings" -> "guogaology:true_omega_leggings";
            case "true_omega_boots" -> "guogaology:true_omega_boots";
            case "hell_true_omega_ore" -> "guogaology:nether_true_omega_ore";
        default -> null;};}
    public static boolean shared(String name){return alias(name)!=null;}
    public static Identifier id(String name){String shared=alias(name);return shared!=null?Identifier.parse(shared):Identifier.fromNamespaceAndPath("guogaology",(name.equals("googology")||name.equals("guogaology"))?"outer":name);}
    public static void initialize(){
        dev.guogaology.outer.registry.ModBlocks.initialize();
        dev.guogaology.outer.registry.ModItems.initialize();
        dev.guogaology.outer.registry.ModEntities.initialize();
        dev.guogaology.outer.registry.ModBoats.initialize();
        dev.guogaology.outer.registry.ModSpawnPlacements.initialize();
        dev.guogaology.outer.registry.ModSpawnEggs.initialize();
        dev.guogaology.outer.registry.ModChunkGenerators.initialize();
        dev.guogaology.outer.registry.ModFeatureTypes.initialize();
    }
}
